Matchtitle: "PetMatch"
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
search_enabled: true
search_tokenizer_separator: /[\s/]+/
mermaid:
  version: "10.5.0" # Optional, fÃ¼r Diagramme
callouts:
  tip:
    title: ğŸ¤ Tipp
    color: blue
  info:
    title: â„¹ï¸ Info
    color: blue
  attention:
    title: â• Achtung
    color: yellow
  download:
    title: ğŸ’¾ Download
<<<<<<< HEAD
    color: grey-dk
=======
    color: grey-dk
>>>>>>> 18680448c266675450e73ada268fda7b33c6a5c9
